### GET para obtener todos los vehiculos
GET http://localhost:6675/vehicles
### GET para obtener todos los vehiculos por año
GET http://localhost:6675/vehicles?year=2018
### GET para obtener un vehiculo por su id.
GET http://localhost:6675/vehicles/ed6a3d5e-3586-11ef-a34c-6c626dedf03d

### POST para agregar un nuevo vehiculo.
POST http://localhost:6675/vehicles
Content-Type: application/json

{
  "name": "Jaguar F",
  "model": "F",
  "year": 2018,
  "description": "The Jaguar F-Type is a two-door, two-seater sports car manufactured by British luxury car manufacturer Jaguar Land Rover.",
  "price": 290.200,
  "urlImage": "https://images.pexels.com/photos/19026324/pexels-photo-19026324/free-photo-of-orange-jaguar-f-type.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
}

### PATCH para actualizar un vehiculo.
PATCH http://localhost:6675/vehicles/ed6a3d5e-3586-11ef-a34c-6c626dedf03d
Content-Type: application/json

{  
  "year": 2020
}
### DELETE para eliminar un vehiculo.
DELETE http://localhost:6675/vehicles/7a45e234-358c-11ef-a34c-6c626dedf03d
