### GET para obtener todos los vehiculos
GET http://localhost:6675/vehicles
### GET para obtener un vehiculo por su id.
GET http://localhost:6675/vehicles/5a1084f4-f890-4f82-830b-9c6fd3f945a6

### POST para agregar un nuevo vehiculo.
POST http://localhost:6675/vehicles
Content-Type: application/json

{
  "name": "Jaguar F",
  "model": "F",
  "year": 2018,
  "description": "The Jaguar F-Type is a two-door, two-seater sports car manufactured by British luxury car manufacturer Jaguar Land Rover.",
  "price": 200000,
  "urlImage": "https://images.pexels.com/photos/19026324/pexels-photo-19026324/free-photo-of-orange-jaguar-f-type.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
}